application: ingobert-app-hrd
version: rev-032
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /
  static_files: index.html
  upload: index.html
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /.*
  script: ingobert.app

libraries:
- name: django
  version: "1.4"
- name: webapp2
  version: "2.5.2"
